Fix docs typos and improve grammar
wptide/docs pull request #45
Opened 2020-04-21 03:23 UTC by akkspros

Fix docs typos and improve grammar

2020-04-22 02:04 UTC, jeffpaul commented on CODE_OF_CONDUCT.md
> +Instances of abusive, harassing or otherwise, unacceptable behavior may be reported by contacting the project team at support@wptide.org. The project team will review and investigate all complaints,
Please revert this change as the punctuation makes sense and it's inherited from the # Contributor Covenant Code of Conduct

2020-04-22 02:07 UTC, jeffpaul commented on docs/gcp/google-app-engine.md
> +You need to setup an App Engine before you can deploy to GCP or use GCP resources for local development.
Please revert this as the existing language makes sense.

2020-05-12 18:33 UTC, jeffpaul commented on docpress/docpress-base/example/README.md
> +Make sure to `rm -rf cache/` first, and restart metal start every time you change Stylus files.
I think this is supposed to be metalsmith, please update to that

2020-05-12 18:36 UTC, jeffpaul requested changes
One more minor change and then this looks good to get merged in.

2020-06-10 02:12 UTC, akkspros commented
@jeffpaul I have updated it when you have a chance, please check this.

2020-06-10 03:00 UTC, jeffpaul approved these changes
Looks good, thanks for updating!

2020-06-10 03:01 UTC, merged